#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Commit added files
#?? 1.0.0
##?
##? Usage:
##?   commit
##?   commit <message>
docs::parse "$@"

if [ -z "$message" ]; then
	git commit
else
	git commit -m"$1"
fi
