[colors.bright]
black = "0x928374"
blue = "0x00C4FF"
cyan = "0x9BE8D8"
green = "0x8EC07C"
magenta = "0xF79BD3"
red = "0xFB4934"
white = "0xebdbb2"
yellow = "0xFABD2F"

[colors.normal]
black = "0x282828"
blue = "0x30A2FF"
cyan = "0x78C1F3"
green = "0x689D6A"
magenta = "0xEA1179"
red = "0xcc241d"
white = "0xA89984"
yellow = "0xFFE17B"

[colors.primary]
background = "0x282828"
foreground = "0xFBF1C7"

[font]
size = 16

[font.bold]
family = "OperatorMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "OperatorMono Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "OperatorMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "OperatorMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 16

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 0.7
startup_mode = "Maximized"
